on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      - name: Deploy WebApp to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "${{ secrets.USERNAME }}"
          server: "${{ secrets.SERVER_IP }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./build/*"
          remote_path: "/srv/who-goes-first/www/"
          args: "-o ConnectTimeout=5"
